### ISSUE TITLE
Window is to large after update

### ISSUE THREAD

**Issue by NathanBnm** [hannesschulze/optimizer#27]
I think it's due to French translations. Here is a screenshot:

![image](https://user-images.githubusercontent.com/45366162/53937402-4d2faa00-40ad-11e9-829e-935b183009e7.png)

Maybe you can adjust this a little bit.

**Comment by hannesschulze** [comment]
This should be fixed in 7d049a61547b2a5a3be3b49530c28a05cc953ff6
