### ISSUE TITLE
Package Caches cleaning tries to find * .deb on fedora

### ISSUE THREAD

**Issue by gavr123456789** [hannesschulze/optimizer#32]
https://i.imgur.com/zvVyoko.png 

Please add some check to the distribution to clean up *rpm. Your app is now in Copr.
https://copr.fedorainfracloud.org/coprs/atim/optimizer/

**Comment by hannesschulze** [comment]
Thanks :) Will definitely do this before I release the next version.

**Comment by gavr123456789** [comment]
just check distro version somewhere there 
![image](https://user-images.githubusercontent.com/30507409/54076218-17abdc00-42ba-11e9-9b57-449eb86eeed5.png)
with something like this https://valadoc.org/glib-2.0/GLib.Process.spawn_command_line_async.html

**Comment by hannesschulze** [comment]
I think I'm going to add a list with locations for some popular distros and if it doesn't contain the current one (don't know how I will check this, but I think I'll find a good option) "Package Caches" just won't appear.

**Comment by hannesschulze** [comment]
I added a check for the package manager in 6acc27089b7f3b2c055ee9901d2472408ddc2d65

However I didn't include an option for dnf. I just added the paths for apt and pacman - I didn't find the exact path for fedora (Stacer doesn't provide one too as far as I know). Feel free to open another issue if you think that's necessary - Optimizer will simply hide the option for now.
