### ISSUE TITLE
Maybe remove Granite dependency

### ISSUE THREAD

**Issue by hannesschulze** [hannesschulze/optimizer#35]
I'm not really sure if I need this anymore.

**TODO:** Find out if it's necessary, if it is, maybe remove references and remove granite as a dependency.

**Comment by gavr123456789** [comment]
++++++++++++++++ Granite is not cross-platform.

**Comment by hannesschulze** [comment]
Unfortunately I don't think I'm able to do this. Optimizer uses Granite in the following ways:

- Settings - I think it would be easy to delete this and use the standard GLib.Settings
- Toasts - This is where it gets tricky. Optimizer uses Toasts to notify the user about the progress in the system cleaner view. I would have to copy some of the code from Granite into my own widget and I don't really want to do that - also to receive updates.

But the main reason for me to keep Granite is #18, which I'm going to implement soon - so I'll keep Granite as a dependency.

Btw, what do you mean by "not cross-platform"? I think Granite is available in nearly every major distro ([Ubuntu](https://packages.ubuntu.com/bionic/libgranite-dev), [Arch](https://www.archlinux.org/packages/community/x86_64/granite/), [Fedora](https://src.fedoraproject.org/rpms/granite), [OpenSuse?](https://software.opensuse.org/package/libgranite5)) currently and I recently even saw somebody compiling it on Windows.

**Comment by gavr123456789** [comment]
Pls share where u see it for windows. in Elementary telegram somebody told me its imposible. 
![image](https://user-images.githubusercontent.com/30507409/54118582-6ebdc800-4404-11e9-8ec4-a415a2fcad47.png)

**Comment by hannesschulze** [comment]
Here's an image from the elementary community Slack showing a DynamicNotebook:

[](https://elementarycommunity.slack.com/files/UD12W7ZPE/FGGC1005Q/image.png)

Anyway, I think optimizer also won't run on windows for other reasons.

**Comment by gavr123456789** [comment]
Oh, yeah, right, it slipped my mind that you absolutely don't need windows support. Optimizer is specific to the Linux platform, but I really want Windows support for independent applications like Minder.
