### ISSUE TITLE
Optimizer now in Fedora repos

### ISSUE THREAD

**Issue by tim77** [hannesschulze/optimizer#39]
Just FYI https://bodhi.fedoraproject.org/updates/optimizer-1.1.0-2.fc29 🙂

How to install:
`sudo dnf install optimizer`

Note: it take some time to sync all mirrors before package will be available for install.

**Comment by hannesschulze** [comment]
That's awesome!

Are you the maintainer? If so, did you enable the fallback theme? - I don't think that the elementary styled progress bars really fit in there :sweat_smile:

**Comment by tim77** [comment]
Thats how its looks for me: 
![optimizer](https://user-images.githubusercontent.com/5614476/54299108-dae62a80-45c2-11e9-94ca-848a2dc1af1f.png)

And i really like how it looks. 😊

**Comment by tim77** [comment]
But dark variant probably require some tweaking:
![dark](https://user-images.githubusercontent.com/5614476/54299439-9018e280-45c3-11e9-957f-b5a838c1bf27.png)

**Comment by hannesschulze** [comment]
Yeah, that's the default elementary style. Here is how it looks like with -Duse_fallback_theme enabled (it's a bit more neutral and just flat):

![Bildschirmfoto vom 2019-03-13 20-19-28](https://user-images.githubusercontent.com/43932053/54308002-564cd980-45cd-11e9-9c09-14c627fd4531.png)

**Comment by tim77** [comment]
So awesome. I will try this too. Flat theme definitely better suit Adwatia new GTK theme.
