### ISSUE TITLE
Optimizer 1.2 crashing on Fedora

### ISSUE THREAD

**Issue by tim77** [hannesschulze/optimizer#56]
Start happens in new 1.2 version. Crashing after 5 seconds. Just quick output from terminal for now:

```
WARNING: Deleting package caches is not supported on this platform.
WARNING: Couldn't read contents of directory - ignoring it
WARNING: Couldn't read contents of directory - ignoring it
WARNING: Couldn't read contents of directory - ignoring it
WARNING: Couldn't read contents of directory - ignoring it
WARNING: Couldn't read contents of directory - ignoring it
WARNING: Couldn't read contents of directory - ignoring it
WARNING: Couldn't read contents of directory - ignoring it
WARNING: Couldn't read contents of directory - ignoring it
WARNING: Couldn't read contents of directory - ignoring it
WARNING: Couldn't read contents of directory - ignoring it
WARNING: Couldn't read contents of directory - ignoring it
Segmentation fault
```

**Comment by hannesschulze** [comment]
Thanks for reporting this. Could you please run Optimizer in gdb and send me the backtrace? :)

**Comment by tim77** [comment]
Done :) [backtrace.log](https://github.com/hannesschulze/optimizer/files/3107667/backtrace.log)

**Comment by hannesschulze** [comment]
Thanks, but it seems like there are no debugging symbols in there - did you install this as a dnf package? Maybe dnf removed them :)

**Comment by tim77** [comment]
Done v2.0 [backtrace.log](https://github.com/hannesschulze/optimizer/files/3107825/backtrace.log)

**Comment by hannesschulze** [comment]
Ah, yup. I think I know where the error is

**Comment by hannesschulze** [comment]
Could you please try #57? I'm not sure if I forgot something and I don't have a fedora system here :)
