### ISSUE TITLE
What do you think about my vision of the icon for Optimizer?

### ISSUE THREAD

**Issue by DanyGee** [hannesschulze/optimizer#79]
![image](https://user-images.githubusercontent.com/26818551/73310839-58d81200-4225-11ea-9723-bc770bcee93e.png)

![image](https://user-images.githubusercontent.com/26818551/73310888-74dbb380-4225-11ea-929f-e64ea17dd90e.png)

![image](https://user-images.githubusercontent.com/26818551/73310936-8e7cfb00-4225-11ea-8f1e-6c2b20f1f355.png)

Download :package: 
[Optimizer.svg.zip](https://github.com/hannesschulze/optimizer/files/4125012/Optimizer.svg.zip)
![0eab647b-90ee-412d-8d6e-85088ccd46b1-7692d7fb-cede-4c34-947c-12129a06b524-v1](https://user-images.githubusercontent.com/26818551/73311297-65a93580-4226-11ea-9fd4-2d40e5eaa8d4.png)

**Comment by msmaldi** [comment]
I prefer your icon

**Comment by hannesschulze** [comment]
Thank you very much for this! After thinking about it I think I can get used to it and the new icon would also finally fix #26.

Could you please open a PR with the new icon?

**Comment by DanyGee** [comment]
I'm glad you like it :heart_eyes: 
I need to prepare all the necessary size versions of the icon - then the PR lands :heavy_check_mark: 
Please give me some time :hourglass_flowing_sand:
