### ISSUE TITLE
Apache won't start after cleaning logs

### ISSUE THREAD

**Issue by drom98** [hannesschulze/optimizer#81]
After cleaning package/application logs apache server won't start giving this error message:
Starting The Apache HTTP Server...
No such file or directory: AH02291: Cannot access directory '/var/log/apache2/' for main error log
The problem is fixed after creating that directory again.

**Comment by hannesschulze** [comment]
Some apps unfortunately seem to depend on specific paths in the log-folder to exist. Please note that this only deleted the logs (as specified in the selection) and not other important data, so the workaround for now is actually creating the directory again – I'm not really sure what's the best way to work around this, either a blacklist or a whitelist. For now, I think this should be discussed in #65; I'll mark this issue as a duplicate

**Comment by tanjilk** [comment]
Just create and giving permisions
`➜  ~ sudo mkdir -p /var/log/apache2/
➜  ~ sudo chmod -R 744 /var/log/apache2/`
